@HostAddress = http://localhost:5000

POST {{HostAddress}}/api/CalculateElo/1200/1000
Accept: application/json

###

POST {{HostAddress}}/api/CalculateElo/1000/1200
Accept: application/json

###

GET {{HostAddress}}/api/GetCarPicture
