// <auto-generated />
using FTB.MinimalAPI.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FTB.MinimalAPI.Migrations
{
    [DbContext(typeof(AutomobileContext))]
    [Migration("20240424214736_Initial Migration")]
    partial class InitialMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.4");

            modelBuilder.Entity("FTB.MinimalAPI.Models.AutomobileModel", b =>
                {
                    b.Property<string>("AutomobileName")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("AutomobileImage")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("TEXT");

                    b.Property<int>("Losses")
                        .HasColumnType("INTEGER");

                    b.Property<double>("Score")
                        .HasColumnType("REAL");

                    b.Property<int>("Wins")
                        .HasColumnType("INTEGER");

                    b.HasKey("AutomobileName");

                    b.ToTable("Automobiles");
                });

            modelBuilder.Entity("FTB.MinimalAPI.Models.VoteModel", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("Car1Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Car2Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<double>("Score")
                        .HasColumnType("REAL");

                    b.Property<string>("Winner")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Votes");
                });
#pragma warning restore 612, 618
        }
    }
}
